# enable mouse and colors
set -g mouse on

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# split panes using | and -
# run new panes with the same directory
unbind '"'
unbind %
bind  |  split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# vim keymap
set -g mode-keys vi

# Use folder name for all tabs
set -g automatic-rename on
set -g allow-rename on
set -g automatic-rename-format " #{b:pane_current_path}"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'laktak/extrakto'

# catpuccin config
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# extrakto config
set -g @extrakto_fzf_tool "$HOME/.fzf/bin/fzf"

# run plugins (should always be last)
run '~/.tmux/plugins/tpm/tpm'

# source env specific config
source-file -q ~/.tmux-ext.conf

