# Font
font_family FiraCode Nerd Font

# Cursor
cursor_shape beam

# Color scheme
foreground #ffffff
background #202020

# Terminal bell
enable_audio_bell no

# Window layout
remember_window_size no
initial_window_width 800
initial_window_height 800

# copy selection
copy_on_select yes
